name: Release charts
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  changed-dirs:
    name: Get changed dirs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      matrix: ${{ steps.changed-dirs.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get changed dirs
        id: changed-dirs
        uses: tj-actions/changed-files@v46
        with:
          matrix: true
          dir_names: true
          dir_names_max_depth: 1
      - name: List all changed dirs
        run: echo '${{ steps.changed-dirs.outputs.all_changed_files }}'

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [changed-dirs]
    # Don't run if no changes in directories other than .github (it's excluded from the matrix below
    if: ${{ needs.changed-dirs.outputs.matrix != '[".github"]' }}
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.changed-dirs.outputs.matrix) }}
        exclude:
          - dir: ".github"
    steps:
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v5
        with:
          fetch-tags: true

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "${{ matrix.dir }}-v"
          fetch_all_tags: true

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Update major tag
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

          export TAG_NAME="${{ steps.tag_version.outputs.new_tag }}"
          export TAG_MAJOR="${TAG_NAME%%.*}"

          git tag --force -a "${TAG_MAJOR}" -m "Release ${TAG_NAME}"
          git push --force origin "${TAG_MAJOR}"
